---
- hosts: slave
  become: True
  tasks:
    - name: Start the container
      docker_container:
        name: smartbuy
        image: "mktraindo/smart:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
