---
- hosts: slave
  become: ansadmin
  tasks:
    - name: Start the container
      docker_container:
        name: smartbuy
        image: "mktraindo/smart:{{BUILD_ID}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
